### PR TITLE
Add an Action class to model permissions and request codes

### PR DESCRIPTION
**Pull request by lgvalle**
- Add `Action` class to group together action request codes and related permission. 
  - Request codes are annotated with `@ActionCode` to help preventing errors.
- Add method `checkGrantedPermission()` to verify if a permission has been granted and callback to appropriate method: `permissionAccepted()` or `permissionDenied()`
- `verifyGrantedPermission()` is now private as it is used only internally

### CODE REVIEW

**Comment by lgvalle** [comment]
@CesarValiente you may want to tweak class names here, as this new `Action` class may not play nicely with your existing `ImageAction`,  `SmsAction` and `PermissionAction`

I would rather call this new class `PermissionAction` actually, but it is a name already taken in this project.

**Comment by CesarValiente** [comment]
@lgvalle What about changing the name of the `Action` class to `PermissionCode` or something like that? Maybe it gives a better understanding about its ActionCodes are used for?

**Comment by CesarValiente** [comment]
Umm don't worry, I'm trying to think any other better name for this class, and as you say, it would fit with `PermissionAction`. What I've said before makes no sense since it's an Action indicator and inside has the `ActionsCode`. So it looks good to me :+1:

**Comment by CesarValiente** [comment]
Thanks for your contribution mate! :smile:

**Comment by lgvalle** [comment]
Thank you for creating this sample! :tophat:

**Pull request merged**
